config/routes.rb
Rails.application.routes.draw do
  resources :boards
  devise_for :users
  resources :labels
  resources :publicaciones
  #root "publicaciones#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  get '/users', to: 'users#home'
  get '/users/:user_id/publicacione', to: 'publicacione#index', as: :user_publications
  root to: "publicacione#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
    belongs_to :user
    belongs_to :publicacione
  end

app/models/label.rb
class Label < ApplicationRecord
  has_and_belongs_to_many :publicaciones
  #has_many :publicaciones, dependent: :destroy
  validates :nombre, presence: true
end

app/models/publicacione.rb
class Publicacione < ApplicationRecord
  belongs_to :user
  belongs_to :label
  has_and_belongs_to_many :label
  has_many :board:scale => has_many :user, through: :boards
  has_one_attached :foto
  validates :titulo, presence: true
  validates :descripcion, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  extend Devise::Models
  devise :devise :database_authenticatable, :registerable
  has_many :boards
  has_many :publicacione, through: :boards
  has_many :publicacione , dependent: :destroy
  accepts_nested_attributes_for :publicacione

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :authenticate_user!
  
    def index
      @boards = Board.all
    end
  
    def show
      board
    end
  
    def new
      @board = current_user.boards.build
    end
  
    def edit
      board
    end
  
    def create
      @board = current_user.boards.build(board_params)
  
      if @board.save
        redirect_to board_url(@board), notice: "tablero creado con exito"
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def update
      if board.update(board_params)
        redirect_to board_url(@board), notice: "tablero actualizado con exito"
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      board.destroy
  
      redirect_to boards_url, notice: "tablero eliminado con exito"
    end
  
    private
  
      def board
        @board = Board.find(params[:id])
      end
  
      def board_params
        params.require(:board).permit(:user, :publicacione)
      end
  end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: %i[ show edit update destroy ]

  # GET /labels or /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1 or /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels or /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to label_url(@label), notice: "Label was successfully created." }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1 or /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to label_url(@label), notice: "Label was successfully updated." }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1 or /labels/1.json
  def destroy
    @label.destroy

    respond_to do |format|
      format.html { redirect_to labels_url, notice: "Label was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def label_params
      params.require(:label).permit(:nombre, :publicaciones_id)
    end
end

app/controllers/publicaciones_controller.rb
class PublicacionesController < ApplicationController
  #before_action :set_publicacione, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]

  # GET /publicaciones or /publicaciones.json
  def index
    @publicaciones = Publicacione.all
  end

  # GET /publicaciones/1 or /publicaciones/1.json
  def show
  end

  # GET /publicaciones/new
  def new
    @publicacione = current_user.publications.build
  end

  # GET /publicaciones/1/edit
  def edit
  end

  # POST /publicaciones or /publicaciones.json
  def create
    @publicacione = current_user.publications.build(publication_params)

    respond_to do |format|
      if @publicacione.save
        format.html { redirect_to publicacione_url(@publicacione), notice: "Publicacione was successfully created." }
        format.json { render :show, status: :created, location: @publicacione }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publicacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publicaciones/1 or /publicaciones/1.json
  def update
    respond_to do |format|
      if @publicacione.update(publicacione_params)
        format.html { redirect_to publicacione_url(@publicacione), notice: "Publicacione was successfully updated." }
        format.json { render :show, status: :ok, location: @publicacione }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publicacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publicaciones/1 or /publicaciones/1.json
  def destroy
    @publicacione.destroy

    respond_to do |format|
      format.html { redirect_to publicaciones_url, notice: "Publicacione was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publicacione
      @publicacione = Publicacione.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publicacione_params
      params.require(:publicatione).permit(:titulo, :descripcion, :label_id, :user_id, :foto)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def home
      @users = User.all
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/publicaciones_helper.rb
module PublicacionesHelper
end

app/views/boards/_board.html.erb
<div id="<%= dom_id board %>">
  <p>
    <strong>Usuario:</strong>
    <%= board.user %>
  </p>

  <p>
    <strong>Publicación:</strong>
    <%= board.publicacione %>
  </p>

</div>

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <% if board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this publicacione from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_area :descripcion %>
  </div>

  <div>
    <%= form.label :foto, style: "display: block" %>
    <%= form.text_field :foto %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editar tablero</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "ver este tablero", @board %> |
  <%= link_to "vover a tablero", boards_path %>
</div>

app/views/boards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tableros</h1>

<div id="boards">
  <% @boards.each do |board| %>
    <%= render board %>
    <p>
      <%= link_to "Ver este tablero", board %>
    </p>
  <% end %>
</div>

<%= link_to "Nuevo Tablero", new_board_path %>

app/views/boards/new.html.erb
<h1>Nuevos tableros</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Volver a los tableros", boards_path %>
</div>

app/views/boards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @board %>

<div>
  <%= link_to "editar tablero", edit_board_path(@board) %> |
  <%= link_to "volver a tablero", boards_path %>

  <%= button_to "eliminar tablero", @board, method: :delete %>
</div>

app/views/labels/_form.html.erb
<%= form_with(model: label) do |form| %>
  <% if label.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
        <% label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/labels/_label.html.erb
<div id="<%= dom_id label %>">
  <p>
    <strong>Nombre:</strong>
    <%= label.nombre %>
  </p>

  <p>
    <strong>Publicaciones:</strong>
    <%= label.publicaciones_id %>
  </p>

</div>

app/views/labels/edit.html.erb
<h1>Editing label</h1>

<%= render "form", label: @label %>

<br>

<div>
  <%= link_to "Show this label", @label %> |
  <%= link_to "Back to labels", labels_path %>
</div>

app/views/labels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Labels</h1>

<div id="labels">
  <% @labels.each do |label| %>
    <%= render label %>
    <p>
      <%= link_to "Show this label", label %>
    </p>
  <% end %>
</div>

<%= link_to "New label", new_label_path %>

app/views/labels/new.html.erb
<h1>New label</h1>

<%= render "form", label: @label %>

<br>

<div>
  <%= link_to "Back to labels", labels_path %>
</div>

app/views/labels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @label %>

<div>
  <%= link_to "Edit this label", edit_label_path(@label) %> |
  <%= link_to "Back to labels", labels_path %>

  <%= button_to "Destroy this label", @label, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Giphy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render 'shared/navbar' %>
      <main class="container">
   
    <%= yield %>
    <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/publicaciones/_form.html.erb
<%= form_with(model: publicacione) do |form| %>
  <% if publicacione.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publicacione.errors.count, "error") %> prohibited this publicacione from being saved:</h2>

      <ul>
        <% publicacione.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_area :descripcion %>
  </div>

  <div>
    <%= form.label :foto, style: "display: block" %>
    <%= form.text_field :foto %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publicaciones/_publicacione.html.erb
<div id="<%= dom_id publicacione %>">
  <p>
    <strong>Titulo:</strong>
    <%= publicacione.titulo %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= publicacione.descripcion %>
  </p>

  <p>
    <strong>Label:</strong>
    <%= publicacione.label.name %>
  </p>

  <p>
    <strong>Usuario:</strong>
    <%= link_to publicacione.usuario_id , user_publicacione_path %>
    <%= link_to publication.usuario_id.email, '/user/:usuario_id/publicacione' %>
  </p>

</div>

app/views/publicaciones/edit.html.erb
<h1>Editar publicaciones</h1>

<%= render "form", publicacione: @publicacione %>

<br>

<div>
  <%= link_to "ver las publicaciones", @publicacione %> |
  <%= link_to "volver a las publicaciones", publicaciones_path %>
</div>

app/views/publicaciones/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Publicaciones</h1>

<div id="publicaciones">
  <% @publicaciones.each do |publicacione| %>
    <%= render publicacione %>
    <p>
      <%= link_to "ver publicaciones", publicacione %>
    </p>
  <% end %>
</div>

<%= link_to "nuevas publicaciones", new_publicacione_path %>

app/views/publicaciones/new.html.erb
<h1>nuevas publicaciones</h1>

<%= render "form", publicacione: @publicacione %>

<br>

<div>
  <%= link_to "volver a las publicaciones", publicaciones_path %>
</div>

app/views/publicaciones/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @publicacione %>

<div>
  <%= link_to "editar publicaciones", edit_publicacione_path(@publicacione) %> |
  <%= link_to "volver a publicaciones", publicaciones_path %>

  <%= button_to "eliminar publicaciones", @publicacione, method: :delete %>
</div>

app/views/users/home.html.erb
<% @users.each do |user| %>
  <p>
    <strong>Usario:</strong>
    <%= usuario_id.email %>
  </p>
<% end %>